Fix placeholders for ignore
crowdin/crowdin-cli pull request #144
Opened 2019-12-06 12:18 UTC by frombetelgeuse

What is done:
- Slightly simplified interface of FileHelper (It is not necessary to solution)
- Added  class to placeholder functionality
- Inserted it where necessary to solve the problem
- Added some tests

2019-12-10 17:56 UTC, yevheniyJ requested changes

2019-12-10 17:56 UTC, yevheniyJ commented on src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
> +            if (!supportedLangs.parallelStream().anyMatch(lang -> lang.getName().equals(projectLang.getName()))) {
outer foreach can be replaced into something like this:
`projectLangs.stream()
  .findFirst(projectLang -> !supportedLangs.stream().anyMatch(lang -> lang.getName().equals(projectLang.getName())))
  .ifPresent(projectLang -> throw new RuntimeException("Proj contains langs that Crowdin doesn't support: " + projectLang.getName()))`;

2019-12-10 17:56 UTC, yevheniyJ commented on src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
> +        if (sources == null || toFormat == null)
add brackets

2019-12-10 17:56 UTC, yevheniyJ commented on src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
> +            res.addAll(format(sources, str, onProjectLangs));
please use `this` keyword when invoking instance methods

2019-12-10 17:56 UTC, yevheniyJ commented on src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
> +        for(Language lang : (onProjectLangs ? projectLangs : supportedLangs)) {
Use streams instead of loops. `langs.stream().flatMap(...)`

2019-12-11 07:47 UTC, andrii-bodnar commented on src/main/java/com/crowdin/cli/properties/helper/FileHelper.java
> +//     * @param fileBean the file bean from the config.
Please update annotations

2019-12-11 07:50 UTC, yevheniyJ approved these changes

2019-12-11 08:44 UTC, andrii-bodnar approved these changes

2019-12-12 15:11 UTC, merged